( button.f )
GPIO_ADDR E4 + CONSTANT PULLUP
GPIO8 CONSTANT BREAK_BUTTON
BREAK_BUTTON GPREN0 ENABLE
BREAK_BUTTON CLEAR_EVENT
: IS_PRESSED GPLEV0 @ AND 0 = IF 1 ELSE 0 THEN ;
: IS_CLICKED GPEDS0 @ AND 0 = IF 0 ELSE 1 THEN ;