( button.f )
GPIO_ADDR E4 + CONSTANT GPIO_PUP_PDN_0
: PULL_UP N_GPIO GPIO_PUP_PDN_0 2DUP SWAP MASK2 SWAP @ AND ROT 1BIT_SET OR SWAP ! ;
: PULL_DOWN N_GPIO GPIO_PUP_PDN_0 2DUP SWAP MASK2 SWAP @ AND ROT 1+ 1BIT_SET OR SWAP ! ;

GPIO9 PULL_UP
GPIO9 CONSTANT BREAK_BUTTON
BREAK_BUTTON GPREN0 ENABLE
BREAK_BUTTON CLEAR_EVENT
: IS_PRESSED GPLEV0 @ AND 0 = IF 1 ELSE 0 THEN ;
: IS_CLICKED GPEDS0 @ AND 0 = IF 0 ELSE 1 THEN ;