( button.f )
GPIO_ADDR E4 + CONSTANT GPIO_PUP_PDN_0
: PULL_UP N_GPIO GPIO_PUP_PDN_0 2DUP SWAP MASK2 SWAP @ AND ROT 1BIT_SET OR SWAP ! ;
: PULL_DOWN N_GPIO GPIO_PUP_PDN_0 2DUP SWAP MASK2 SWAP @ AND ROT 1+ 1BIT_SET OR SWAP ! ;

: INIT_BUTTON
    GPIO9 INPUT 
    GPIO10 INPUT
    GPIO9 PULL_UP 
    GPIO10 PULL_UP
    GPIO9 GPREN0 ENABLE 
    GPIO10 GPREN0 ENABLE
    GPIO9 GPIO10 OR CLEAR_EVENT ;

GPIO9 CONSTANT BREAK_BUTTON
GPIO10 CONSTANT EXIT_BUTTON

: IS_PRESSED GPLEV0 @ AND 0 = IF 1 ELSE 0 THEN ;
: IS_CLICKED GPEDS0 @ AND 0 = IF 0 ELSE 1 THEN ;