GPIO5 CONSTANT BUTTON5
GPIO6 CONSTANT BUTTON6
GPIO7 CONSTANT BUTTON7
GPIO8 CONSTANT BUTTON8

BUTTON5 GPREN0 ENABLE
BUTTON6 GPREN0 ENABLE
BUTTON7 GPREN0 ENABLE
BUTTON8 GPREN0 ENABLE

: BUTTONS_RESET BUTTON5 BUTTON6 OR BUTTON7 OR BUTTON8 OR CLEAR_EVENT ;

: SEQUENZA 8 = -ROT 6 = -ROT 5 = -ROT 2SWAP SWAP 7 = ; ( ordine 7 5 6 8 )
: RESET STACK_CLEAR
        GPEDS0 @ 0<> IF
        BUTTONS_RESET THEN
;

: CHECK
    BEGIN
        RESET  
        ." DIGITA IL PIN E PREMI INVIO "
        BEGIN
            BUTTON7 IS_CLICKED IF
            ." 7 " BUTTON7 N_GPIO BUTTON7 CLEAR_EVENT THEN

            BUTTON5 IS_CLICKED IF
            ." 5 " BUTTON5 N_GPIO BUTTON5 CLEAR_EVENT THEN 

            BUTTON6 IS_CLICKED IF
            ." 6 " BUTTON6 N_GPIO BUTTON6 CLEAR_EVENT THEN

            BUTTON8 IS_CLICKED IF
            ." 8 " BUTTON8 N_GPIO BUTTON8 CLEAR_EVENT THEN

        BREAK_BUTTON IS_CLICKED
        UNTIL
        BREAK_BUTTON CLEAR_EVENT

        0.5SEC YELLOW BLINK

        DEPTH 4 <> IF
            STACK_CLEAR
            FALSE
            ." ERRATA " CR
            0.5SEC RED BLINK 
        ELSE
            SEQUENZA
            AND AND AND
            DUP FALSE = IF
                ." ERRATA " CR
                0.5SEC RED BLINK
            THEN 
        THEN 
    TRUE =
    UNTIL
    BREAK_BUTTON CLEAR_EVENT
    1 SEC GREEN BLINK
    ." CORRETTA " CR
    RESET
    1
;