GPIO5 CONSTANT BUTTON5
GPIO6 CONSTANT BUTTON6
GPIO7 CONSTANT BUTTON7

BUTTON5 GPREN0 ENABLE
BUTTON6 GPREN0 ENABLE
BUTTON7 GPREN0 ENABLE

BUTTON5 BUTTON6 OR BUTTON7 OR CLEAR_EVENT

: SEQUENZA 6 = -ROT 5 = -ROT 7 = -ROT ; ( ordine 7 5 6 )
: RESET STACK_CLEAR
        GPEDS0 @ 0<> IF
        BUTTON5 BUTTON6 OR BUTTON7 OR CLEAR_EVENT THEN
;

: CHECK
    BEGIN
        RESET  
        ." DIGITA LA SEQUENZA E PREMI INVIO "
        BEGIN
            1 SEC DELAY

            BUTTON7 IS_CLICKED IF
            ." 7 " BUTTON7 N_GPIO BUTTON7 CLEAR_EVENT THEN

            BUTTON5 IS_CLICKED IF
            ." 5 " BUTTON5 N_GPIO BUTTON5 CLEAR_EVENT THEN 

            BUTTON6 IS_CLICKED IF
            ." 6 "BUTTON6 N_GPIO BUTTON6 CLEAR_EVENT THEN

        BREAK_BUTTON IS_CLICKED
        UNTIL
        BREAK_BUTTON CLEAR_EVENT

        0.5SEC YELLOW BLINK

        DEPTH 3 > DEPTH 3 < OR IF
            STACK_CLEAR
            FALSE
            ." ERRATA " CR
            0.5SEC RED BLINK 
        ELSE
            SEQUENZA
            ." CONTROLLO SEQUENZA " CR
            AND AND
            DUP FALSE = IF
                ." ERRATA " CR
                0.5SEC RED BLINK
            THEN 
        THEN 
    TRUE =
    UNTIL
    BREAK_BUTTON CLEAR_EVENT
    1 SEC GREEN BLINK
    ." CORRETTA " CR
    RESET
;